import type { NextPage } from 'next'
import Head from 'next/head'
import { PageTemplate } from '../components/page-template/page-template'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ninja Mail</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageTemplate>
        Divulgação
        <br />
        Vídeo
        <br />
        Tumbs
        <br />
        Case Study
        <br />
        Brands
        <br />
        Get Started
        <br />
      </PageTemplate>
    </div>
  )
}

export default Home
